export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  abm: {
    overview: '/dashboard',
    accounts: '/dashboard/accounts',
    account: (id: string) => `/dashboard/accounts/${id}`,
    activity: '/dashboard/activity',
    lanes: '/dashboard/lanes',
    people: '/dashboard/people',
    missions: '/dashboard/missions',
    mission: (id: string) => `/dashboard/missions?id=${id}`,
    workQueue: '/dashboard/work-queue',
    programs: '/dashboard/programs',
    program: (id: string) => `/dashboard/programs?id=${id}`,
    leadRequests: '/dashboard/lead-requests',
    admin: '/dashboard/admin',
    adminEventRules: '/dashboard/admin?tab=event-rules',
    adminPromptTemplates: '/dashboard/admin?tab=prompt-templates',
    adminMissionTemplates: '/dashboard/admin?tab=mission-templates',
    adminJobs: '/dashboard/admin?tab=jobs',
    adminProcurement: '/dashboard/admin?tab=procurement',
    howItWorks: '/dashboard/how-it-works',
  },
  dashboard: {
    overview: '/dashboard',
    nodes: '/dashboard/nodes',
    ports: '/dashboard/ports',
    scheduler: '/dashboard/scheduler',
    usage: '/dashboard/usage',
    security: '/dashboard/security',
    incidents: '/dashboard/incidents',
    audit: '/dashboard/audit',
    billing: '/dashboard/billing',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    docs: '/dashboard/docs',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
